services:
    app.admin.grupo:
        class: AppBundle\Admin\GrupoAdmin
        arguments: [~, AppBundle\Entity\Grupo, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Grupos, label: Grupo }
        public: true

    app.admin.grupos_usuarios:
        class: AppBundle\Admin\GruposUsuariosAdmin
        arguments: [~, AppBundle\Entity\GruposUsuarios, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Grupos, label: GruposUsuarios }
        public: true

    app.admin.universidad:
        class: AppBundle\Admin\UniversidadAdmin
        arguments: [~, AppBundle\Entity\Universidad, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Universidades, label: Universidad }
        public: true

    app.admin.especialidad:
        class: AppBundle\Admin\EspecialidadAdmin
        arguments: [~, AppBundle\Entity\Especialidad, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Universidades, label: Especialidad }
        public: true

    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Usuarios, label: Usuarios }
        public: true

    app.admin.cuadrante:
        class: AppBundle\Admin\CuadranteAdmin
        arguments: [~, AppBundle\Entity\Cuadrante, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Cuadrantes, label: Cuadrante }
        public: true

    app.admin.cuadrante_dia:
        class: AppBundle\Admin\CuadranteDiaAdmin
        arguments: [~, AppBundle\Entity\CuadranteDia, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Cuadrantes, label: Fechas Cuadrante }
        public: true

    app.admin.muestra:
        class: AppBundle\Admin\MuestraAdmin
        arguments: [~, AppBundle\Entity\Muestra, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Muestras, label: Muestras }
        public: true

    app.admin.grupo_muestra:
        class: AppBundle\Admin\GrupoMuestraAdmin
        arguments: [~, AppBundle\Entity\GrupoMuestra, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Muestras, label: Grupo-Muestra }
        public: true

    app.admin.usuarios_muestras:
        class: AppBundle\Admin\UsuariosMuestrasAdmin
        arguments: [~, AppBundle\Entity\UsuariosMuestras, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Muestras, label: Usuarios-Muestras }
        public: true
